### ISSUE TITLE
Codota Al Algorithm

### ISSUE THREAD

**Issue by MbProg** [codota/codota-maven-plugin#5]
In your web site it states: 

> Codota is free and will always be free when serving results based on publicly available code.

If I understand this sentence correctly, it means that the source code of Codota is publicly available. If yes, where can I find the source code of the AI algorithms and modelling approaches you are using. 
If not, could you explain which AI algorithms you are using and how you are modelling the data?

**Comment by drorweiss** [comment]
Hi @MbProg - The Codota AI algorithms are currently closed-source and not publicly available.
The sentence you quoted means that you can use Codota for free to get code suggestions based on training data from publicly available code. I now see that the sentence is somewhat ambiguous and we need to clarify it.
You can look at http://www.cs.technion.ac.il/~yahave/ to learn about the science behind Codota - hope it helps.
